### ISSUE TITLE
[FEATURE REQUEST]  GNOME accent color support?

### ISSUE THREAD

**Issue by CodedIsTaken** [largestgithubuseronearth/addwater#36] opened 2024-12-02 21:16 UTC
add the ability to change the accent color on the settings page.

**Comment by largestgithubuseronearth** [comment] 2024-12-03 01:10
Accent color support has already been implemented into the Firefox GNOME Theme itself and is available with v133.

Closing this now but let me know if you have any other issues. Thanks.

**Closed by largestgithubuseronearth** 2024-12-03 01:10 UTC
Labels: feature request

**Comment by CodedIsTaken** [comment] 2024-12-03 01:12
> Accent color support has already been implemented into the Firefox GNOME Theme itself and is available with v133.
> 
> Closing this now but let me know if you have any other issues. Thanks.


somehow it's not working for me and it's still on blue.

**Comment by largestgithubuseronearth** [comment] 2024-12-03 03:08
Go to the "Customize Toolbar" menu of Firefox and check that the Firefox GNOME Theme version is v133. If it's lower, then you have to update the theme.

The only issue I've seen regarding the accent not working is [this issue](https://github.com/rafaelmardojai/firefox-gnome-theme/issues/871). They concluded that the cause was from adw-gtk3 which sets the accent strictly to blue. adw-gtk3 has a way to change it manually [here](https://github.com/lassekongo83/adw-colors/tree/main/accent-color-change).

If those don't solve it, there's not enough information here to know what the issue could be otherwise. Please open an issue for the [Firefox GNOME Theme](https://github.com/rafaelmardojai/firefox-gnome-theme) if you've checked both of these and it's still not working.
