### ISSUE TITLE
[BUG] Tap loading circle's color is same as tab's color in hovering (In dark mode)

### ISSUE THREAD

**Issue by RZHSSNZDH** [largestgithubuseronearth/addwater#23] opened 2024-10-20 19:08 UTC
**Describe the bug**
When user hovers on a tab in dark mode, tab's color changes to a color like gray which the circle that appears when tab is loading has the same color, so the circle is not be visible.

**To Reproduce**
1. Set GNOME to dark mode.
2. Go to a link in the browser.
3. Hover on the loading tab.
4. See error. (You can't see the loading circle)

**Expected behavior**
The circle and the hovered tab's color should be defferent.

**Technical Details (please complete the following information):**
```
 - Distribution: Arch
 - Add Water version: v1.1.1
 - Browser: Firefox
 - Browser Package: Base
 - Browser Version: v131.0.3
```

**Comment by largestgithubuseronearth** [comment] 2024-10-20 19:17
So you're saying that the spinner on the left side of a tab is invisible when you hover over it?

**Comment by largestgithubuseronearth** [comment] 2024-10-20 19:18
It's hard to tell what you're talking about without a screenshot...

**Comment by largestgithubuseronearth** [comment] 2024-10-20 19:22
I've tried to replicate this with and without "Active Tab Contrast" enabled but the "loading" spinner is still visible. 
![image](https://github.com/user-attachments/assets/853c306f-c67c-4004-bf32-c35da32f0f70)

What theme options do you have enabled?

**Comment by RZHSSNZDH** [comment] 2024-10-20 19:28
I mean this. In one of screetshots I hovered the loading tab so the spinner is invisible and in the otherone I hovered on another tab, so the loading tab's spinner is visible:
![نماگرفت از 2024-10-20 22-53-16](https://github.com/user-attachments/assets/fc3b336a-c5bc-49cf-8b1c-1497a6d844fb)
![نماگرفت از 2024-10-20 22-52-52](https://github.com/user-attachments/assets/d674569d-5e0d-427a-bdcf-97cdcfc67b5b)
This is my options enabled:
![image](https://github.com/user-attachments/assets/9c98030b-3142-4a71-b0a8-a2a82097ddba)

**Comment by RZHSSNZDH** [comment] 2024-10-20 19:30
In the first screenshot the flathub is loading, but the spinner is not visible because the tab is active. In the second one the right tab is loading and its spinner is visible because another tab is active.

And about the options, I have enabled the options you see in the last screenshot and other options are disabled.

**Comment by largestgithubuseronearth** [comment] 2024-10-20 19:51
Okay. After some testing, it's clear the issue isn't the color of the spinner. The Firefox Theme just isn't designed with right-to-left text in mind.

The tab alignment is completely broken so the spinner isn't visible at all. This is also why the Tab titles aren't centered for you, whereas in left-to-right languages it _is_ center-aligned.

Unfortunately, I can't fix it myself because it's an upstream issue. I'm making an issue over there to let the theme developer know

**Comment by largestgithubuseronearth** [comment] 2024-10-20 20:14
You can track the status on this issue at this link. I can't make any promise of if or when it will be fixed unfortunately.
https://github.com/rafaelmardojai/firefox-gnome-theme/issues/847

Sorry I couldn't be of more help, but thank you for bringing it to my attention.

**Closed by largestgithubuseronearth** 2024-10-20 20:14 UTC
Labels: bug
